
const D=window.PROJECT_DATA,app=document.getElementById('app');document.getElementById('home').onclick=renderClasses;
const sl=s=>({finished:"🟢 Terminado",development:"🟡 En desarrollo",received:"🔵 Contenido recibido",prepared:"⚪ Preparado",closed:"🔒 Cerrado"}[s]||s);
function renderClasses(){app.innerHTML=`<section class="hero"><small>PROYECTO AULA 0.5</small><h1>Clases de español paso a paso</h1><p>Estructura central escalable para todas las clases.</p></section><h2>Clases</h2><div class="grid">${D.classes.map(c=>`<div class="card"><h3>${c.label}</h3><p>4 bloques anuales</p><button onclick="renderSemesters('${c.id}')">Abrir</button></div>`).join('')}</div>`}
function renderSemesters(id){const c=D.classes.find(x=>x.id===id);app.innerHTML=`<div class="path">Inicio › ${c.label}</div><section class="hero"><h1>${c.label}</h1><p>Primer semestre A/B · Segundo semestre A/B</p></section><div class="grid">${c.semesters.map((s,i)=>`<div class="card"><h3>${s.label}</h3><p>${s.vocab.length+s.grammar.length} temas cargados</p><span class="status">${sl(s.status)}</span><button onclick="renderSemester('${id}',${i})">Abrir</button></div>`).join('')}</div>`}
function renderSemester(id,i){const c=D.classes.find(x=>x.id===id),s=c.semesters[i];app.innerHTML=`<div class="path">Inicio › ${c.label} › ${s.label}</div><section class="hero"><h1>${c.label} · ${s.label}</h1><p>Todo el contenido visible de un vistazo.</p></section><h2>📚 Vocabulario</h2><div class="grid">${s.vocab.length?s.vocab.map(t=>card(t,id,i)).join(''):'<div class="card"><p>Sin contenido todavía.</p></div>'}</div><h2>✏️ Gramática</h2><div class="grid">${s.grammar.length?s.grammar.map(t=>card(t,id,i)).join(''):'<div class="card"><p>Sin contenido todavía.</p></div>'}</div>`}
function card(t,id,i){const x=D.topics[t];return `<div class="card"><h3>${x.title}</h3><p>${x.kind}</p><span class="status">${sl(x.status)}</span><button onclick="renderTopic('${t}','${id}',${i})">Abrir tema</button></div>`}
function renderTopic(t,id,i){const c=D.classes.find(x=>x.id===id),s=c.semesters[i],x=D.topics[t];app.innerHTML=`<div class="path">Inicio › ${c.label} › ${s.label} › ${x.title}</div><div class="topic-head"><h1>${x.title}</h1><button class="secondary" onclick="renderSemester('${id}',${i})">← Todos los temas</button></div><div class="note"><b>Estado:</b> ${sl(x.status)}${x.note?' · '+x.note:''}</div>${x.activities.map((a,k)=>`<div class="activity ${a.weight>=3?'high':''}"><strong>${k+1}. ${a.name}</strong><span>${a.items} ${a.items===1?'tarea':'ejercicios'} · peso ×${a.weight}</span></div>`).join('')}`}
renderClasses();
