
const app=document.getElementById('app'),A=window.AULA;let current=null,chosen={},score=0,done={};
function home(){current=null;app.innerHTML=`<section class="hero"><small>VERSIÓN 0.6</small><h1>Clases de español paso a paso</h1><p>Vista general clara · práctica progresiva · autocorrección</p></section><h2>Clases</h2><div class="grid">${Object.keys(A.data.classes).map(c=>`<div class="card"><h3>Clase ${c}</h3><span class="label">4 bloques</span><p>Contenido curricular real ya incorporado.</p><button class="open" onclick="showClass('${c}')">Abrir clase</button></div>`).join('')}</div>`}
function showClass(c){let ss=A.data.classes[c];app.innerHTML=`<div class="path">Inicio › Clase ${c}</div><section class="hero"><h1>Clase ${c}</h1><p>Elige un bloque del curso.</p></section><div class="grid">${Object.keys(ss).map((s,i)=>`<div class="card"><h3>${s}</h3><p>${ss[s].length} apartados · Vocabulario y Gramática</p><button class="open" onclick="showSem('${c}',${i})">Abrir</button></div>`).join('')}</div>`}
function showSem(c,i){let names=Object.keys(A.data.classes[c]),s=names[i],items=A.data.classes[c][s];app.innerHTML=`<div class="path">Inicio › Clase ${c} › ${s}</div><button class="back" onclick="showClass('${c}')">← Clase ${c}</button><section class="hero"><h1>Clase ${c} · ${s}</h1><p>Los apartados con 🟢 ya contienen actividades funcionales.</p></section><div class="grid">${items.map((x,j)=>`<div class="card"><h3>${x[0]}</h3><span class="label">${x[2]=='contenido'?'🔵 Contenido cargado':'🟢 Interactivo'}</span><p>${x[1]}</p><button class="open" onclick="showSection('${c}',${i},${j})">Abrir</button></div>`).join('')}</div>`}
function showSection(c,si,ii){let s=Object.keys(A.data.classes[c])[si],x=A.data.classes[c][s][ii],acts=A.activities[x[2]]||[];current=x[2];chosen={};score=0;done={};let max=acts.reduce((n,a)=>n+a.p,0);app.innerHTML=`<div class="path">Inicio › Clase ${c} › ${s} › ${x[0]}</div><button class="back" onclick="showSem('${c}',${si})">← Vista general</button><section class="hero"><h1>${x[0]}</h1><p>${x[1]}</p></section>${acts.length?`<div class="score"><span>Puntos</span><span id="score">0 / ${max}</span></div>${acts.map((a,i)=>render(a,i)).join('')}`:`<div class="card"><h3>🔵 Contenido incorporado</h3><p>Este apartado ya forma parte de la estructura 0.6. Sus actividades se desarrollarán progresivamente.</p></div>`}`}
function render(a,i){return `<div class="act ${a.x?'extra':''}"><span class="pts">+${a.p} puntos</span><h3>${a.t}</h3><p>${a.q}</p><div class="opts">${a.o.map(o=>`<button class="opt" onclick='pick(${i},this,${JSON.stringify(o)})'>${o}</button>`).join('')}</div><button class="check" onclick="check(${i})">Comprobar</button><div id="f${i}" class="feedback"></div></div>`}
function pick(i,b,v){b.parentElement.querySelectorAll('.opt').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');chosen[i]=v}
function check(i){if(done[i])return;let a=A.activities[current][i],f=document.getElementById('f'+i);if(chosen[i]===a.a){done[i]=1;score+=a.p;f.className='feedback ok';f.textContent='✓ Correcto. Has sumado '+a.p+' puntos.';document.getElementById('score').textContent=score+' / '+A.activities[current].reduce((n,x)=>n+x.p,0)}else{f.className='feedback no';f.textContent='Todavía no. Inténtalo otra vez.'}}
home();
