import {catalog} from './data/catalog.js';
import {renderActivity,bindActivities} from './ui/activityEngine.js';

const app=document.getElementById('app');
let teacher=false;
let view={screen:'home'};

function topbar(){return `<header class="topbar"><div><b>Clases de español paso a paso</b><small>Proyecto Aula · 0.8</small></div><div class="top-actions"><button class="ghost" id="modeBtn">${teacher?'Alumno':'Profesora'}</button><button class="ghost" id="homeBtn">Inicio</button></div></header>`}
function shell(content){app.innerHTML=topbar()+content;document.getElementById('homeBtn').onclick=()=>{teacher=false;view={screen:'home'};render()};document.getElementById('modeBtn').onclick=()=>{teacher=!teacher;render()}}
function render(){if(teacher)return renderTeacher();const course=catalog.find(c=>c.id===view.courseId);const semester=course?.semesters?.find(s=>s.id===view.semesterId);const topic=semester?.topics?.find(t=>t.id===view.topicId);if(topic)return renderTopic(course,semester,topic);if(semester)return renderSemester(course,semester);if(course)return renderCourse(course);renderHome()}
function renderHome(){shell(`<main class="page"><section class="hero"><span class="eyebrow">ARQUITECTURA 0.8</span><h1>Proyecto Aula</h1><p>Interfaz estable, contenido separado y actividades reutilizables.</p></section><section><h2>Clases</h2><div class="grid">${catalog.map(c=>`<button class="card course-card" data-id="${c.id}"><span class="badge">${c.status==='active'?'En desarrollo':c.status==='next'?'Siguiente prioridad':'Preparada'}</span><h3>${c.title}</h3><p>${c.id==='6G'?'Primer bloque modelo ya funcional.':c.id==='7G'?'Estructura preparada para crecer sobre el mismo motor.':'Contenido conectado al mismo sistema.'}</p></button>`).join('')}</div></section></main>`);document.querySelectorAll('.course-card').forEach(b=>b.onclick=()=>{view={screen:'course',courseId:b.dataset.id};render()})}
function renderCourse(course){shell(`<main class="page"><button class="crumb" id="back">← Inicio</button><section class="hero"><span class="eyebrow">${course.id}</span><h1>${course.title}</h1><p>Cuatro bloques anuales con la misma navegación.</p></section><div class="grid">${course.semesters?.length?course.semesters.map(s=>`<button class="card semester-card" data-id="${s.id}" ${s.status==='active'?'':'disabled'}><span class="badge ${s.status}">${s.status==='active'?'Disponible':'Preparado'}</span><h3>${s.title}</h3><p>${s.description||'La estructura está lista para incorporar contenido.'}</p></button>`).join(''):'<div class="panel"><p>Esta clase está conectada a la arquitectura común, pero su contenido aún no está incorporado.</p></div>'}</div></main>`);document.getElementById('back').onclick=()=>{view={screen:'home'};render()};document.querySelectorAll('.semester-card:not([disabled])').forEach(b=>b.onclick=()=>{view={screen:'semester',courseId:course.id,semesterId:b.dataset.id};render()})}
function renderSemester(course,semester){const kinds=['Vocabulario','Gramática','Microbloque'];shell(`<main class="page"><button class="crumb" id="back">← ${course.title}</button><section class="hero"><span class="eyebrow">${course.id} · ${semester.title}</span><h1>Elige qué quieres practicar</h1><p>Gramática y vocabulario aparecen separados, pero reutilizan el mismo motor de actividades.</p></section>${kinds.map(kind=>{const ts=(semester.topics||[]).filter(t=>t.kind===kind);return ts.length?`<section><h2>${kind==='Vocabulario'?'📚':kind==='Gramática'?'✏️':'🧩'} ${kind}</h2><div class="grid">${ts.map(t=>`<button class="card topic-card" data-id="${t.id}"><h3>${t.icon} ${t.title}</h3><p>${t.activities.length} actividad${t.activities.length===1?'':'es'}</p></button>`).join('')}</div></section>`:''}).join('')}</main>`);document.getElementById('back').onclick=()=>{view={screen:'course',courseId:course.id};render()};document.querySelectorAll('.topic-card').forEach(b=>b.onclick=()=>{view={screen:'topic',courseId:course.id,semesterId:semester.id,topicId:b.dataset.id};render()})}
function renderTopic(course,semester,topic){shell(`<main class="page"><button class="crumb" id="back">← Vista general</button><section class="hero"><span class="eyebrow">${topic.kind}</span><h1>${topic.icon} ${topic.title}</h1></section>${topic.explanation?`<section class="explain">${topic.explanation.map(x=>`<p>${x}</p>`).join('')}</section>`:''}<section class="activity-stack" id="activities">${topic.activities.map((a,i)=>renderActivity(a,i)).join('')}</section></main>`);document.getElementById('back').onclick=()=>{view={screen:'semester',courseId:course.id,semesterId:semester.id};render()};bindActivities(document.getElementById('activities'),topic.activities)}
function renderTeacher(){shell(`<main class="page"><section class="hero"><span class="eyebrow">ZONA DE PROFESORA</span><h1>Herramientas docentes</h1><p>Espacio separado para crear, editar y reutilizar material sin mezclarlo con la vista del alumno.</p></section><div class="grid"><div class="panel"><h3>📝 Crear control</h3><p>Seleccionar clase, bloque, vocabulario y gramática. Próxima fase: generar y editar antes de imprimir.</p></div><div class="panel"><h3>🧰 Banco de actividades</h3><p>Actividades reutilizables, con variantes G/R y niveles básico, repaso y desafío.</p></div><div class="panel"><h3>✏️ Editar contenido</h3><p>La edición queda prevista como función central de la zona docente.</p></div></div></main>`)}
render();
